[package]
# Semantic Versionning is used: https://semver.org/
version = "0.0.2"

preview_image = "data/preview.png"

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "data/icon.png"

# The title and description fields are primarily for displaying extension info in UI
title = "HumanGenerator"
description="Human Generator for Omniverse. Create and customize humans in your Omniverse scenes."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Services"

feature = true

# Keywords for the extension
keywords = ["kit", "makehuman","human","character","generator","person"]


# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}
"omni.usd" = {}
"omni.anim.skelJoint" = {}
"omni.kit.browser.core" = {}
"omni.kit.browser.folder.core" = {}

# Main python module this extension provides, it will be publicly available as "import omni.hello.world".
[[python.module]]
name = "siborg.create.human"

[settings]
exts."siborg.create.human.browser.asset".instanceable = []
exts."siborg.create.human.browser.asset".timeout = 10